# Nombre del proyecto
spring.application.name=Unipracticas


# Conexión con PostgreSQL
#/* la base de datos que creo en postgres db_unipracticas */
spring.datasource.url=jdbc:postgresql://localhost:5432/db_unipracticas

# /* el usuario que creo en postgres */
spring.datasource.username=user_java 

 #/* la contraseña que creo en postgres */   
spring.datasource.password=0000            



spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Puerto del proyecto
server.port=8081

# Thymeleaf
spring.thymeleaf.cache=false